.PHONY: major minor patch premajor preminor prepatch prerelease manual

major:
	@cd version && bash ./version.sh major

minor:
	@cd version && bash ./version.sh minor

patch:
	@cd version && bash ./version.sh patch

premajor:
	@cd version && bash ./version.sh premajor

preminor:
	@cd version && bash ./version.sh preminor

prepatch:
	@cd version && bash ./version.sh prepatch

prerelease:
	@cd version && bash ./version.sh prerelease

manual:
	@cd version && bash ./version.sh manual $(v)
